update

diff --git a/.github/workflows/release-linux.yml b/.github/workflows/release-linux.yml
--- a/.github/workflows/release-linux.yml
+++ b/.github/workflows/release-linux.yml
@@ -197,3 +197,30 @@ jobs:
           asset_path: ${{ env.RELEASE_BASENAME }}/sdk/sbf-sdk.tar.bz2
           asset_name: sbf-sdk.tar.bz2
           asset_content_type: application/x-bzip2
+
+      # Rename Version YAML to Match Tarball
+      - name: Rename Version YAML
+        run: |
+          VERSION_YML_PATH="${{ env.RELEASE_BASENAME }}/version.yml"
+          RENAMED_YML="${{ env.TARBALL_BASENAME }}-x86_64-unknown-linux-gnu.yml"
+
+          if [ -f "$VERSION_YML_PATH" ]; then
+            echo "Renaming $VERSION_YML_PATH to $RENAMED_YML..."
+            cp "$VERSION_YML_PATH" "$RENAMED_YML"
+          else
+            echo "Error: version.yml does not exist!"
+            exit 1
+          fi
+          echo "Renamed version.yml: $RENAMED_YML"
+
+      # Upload Renamed Version YAML
+      - name: Upload Version YAML
+        if: inputs.skip_sbf_sdk == 'false'
+        uses: actions/upload-release-asset@v1
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          upload_url: ${{ github.event.release.upload_url }}
+          asset_path: solana-release-x86_64-unknown-linux-gnu.yml
+          asset_name: solana-release-x86_64-unknown-linux-gnu.yml
+          asset_content_type: text/yaml
diff --git a/.github/workflows/release-windows.yml b/.github/workflows/release-windows.yml
--- a/.github/workflows/release-windows.yml
+++ b/.github/workflows/release-windows.yml
@@ -175,3 +175,29 @@ jobs:
           asset_path: ${{ env.RELEASE_BASENAME }}/bin/agave-install-init-${{ env.TARGET }}.exe
           asset_name: agave-install-init-${{ env.target }}
           asset_content_type: application/octet-stream
+
+      # Rename Version YAML to Match Tarball
+      - name: Rename Version YAML
+        run: |
+          VERSION_YML_PATH="${{ env.RELEASE_BASENAME }}/version.yml"
+          RENAMED_YML="${{ env.TARBALL_BASENAME }}-${{ env.target }}.yml"
+
+          if [ -f "$VERSION_YML_PATH" ]; then
+            echo "Renaming $VERSION_YML_PATH to $RENAMED_YML..."
+            cp "$VERSION_YML_PATH" "$RENAMED_YML"
+          else
+            echo "Error: version.yml does not exist!"
+            exit 1
+          fi
+          echo "Renamed version.yml: $RENAMED_YML"
+
+      # Upload Renamed Version YAML
+      - name: Upload Version YAML
+        uses: actions/upload-release-asset@v1
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          upload_url: ${{ github.event.release.upload_url }}
+          asset_path: ${{ env.TARBALL_BASENAME }}-${{ env.target }}.yml
+          asset_name: ${{ env.TARBALL_BASENAME }}-${{ env.target }}.yml
+          asset_content_type: text/yaml
